title: Preston Ching
logo: 'android-chrome-192x192.png' # you can add own logo.
description: Preston Ching's Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.prestonching.com/" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Preston Ching
  image: '/assets/img/Profile_Pic.jpg'
  job: Preston Ching
  bio: Aspiring Economist, Tech Enthusiast, Avid Investor, Spirited Musician.
  email: prestonching7@gmail.com


# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/
  - name: Facebook
    link: https://facebook.com/
  - name: Instagram
    link: https://instagram.com/


# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-205055388-1 # add your identifier. For example UA-99631805-1.

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-paginate

paginate: 5

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
